// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TableUp.Infrastructure.Persistence;

#nullable disable

namespace TableUp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TableUpDbContext))]
    [Migration("20260608141641_AddSnakeCaseOnDB")]
    partial class AddSnakeCaseOnDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TableUp.Domain.Entities.MenuCategory", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_guid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_guid");

                    b.HasKey("Guid")
                        .HasName("pk_menu_categories");

                    b.HasIndex("CreatedByGuid")
                        .HasDatabaseName("ix_menu_categories_created_by_guid");

                    b.HasIndex("RestaurantGuid")
                        .HasDatabaseName("ix_menu_categories_restaurant_guid");

                    b.HasIndex("UpdatedByGuid")
                        .HasDatabaseName("ix_menu_categories_updated_by_guid");

                    b.ToTable("menu_categories", (string)null);
                });

            modelBuilder.Entity("TableUp.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<Guid>("CategoryGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("category_guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_guid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_guid");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Guid")
                        .HasName("pk_menu_items");

                    b.HasIndex("CategoryGuid")
                        .HasDatabaseName("ix_menu_items_category_guid");

                    b.HasIndex("CreatedByGuid")
                        .HasDatabaseName("ix_menu_items_created_by_guid");

                    b.HasIndex("UpdatedByGuid")
                        .HasDatabaseName("ix_menu_items_updated_by_guid");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("TableUp.Domain.Entities.OrderBill", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_guid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StatusOrderBill")
                        .HasColumnType("integer")
                        .HasColumnName("status_order_bill");

                    b.Property<Guid>("TableGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("table_guid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_guid");

                    b.HasKey("Guid")
                        .HasName("pk_order_bills");

                    b.HasIndex("CreatedByGuid")
                        .HasDatabaseName("ix_order_bills_created_by_guid");

                    b.HasIndex("TableGuid")
                        .HasDatabaseName("ix_order_bills_table_guid");

                    b.HasIndex("UpdatedByGuid")
                        .HasDatabaseName("ix_order_bills_updated_by_guid");

                    b.ToTable("order_bills", (string)null);
                });

            modelBuilder.Entity("TableUp.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_guid");

                    b.Property<Guid>("MenuItemGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_guid");

                    b.Property<Guid>("OrderBillGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("order_bill_guid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StatusOrderItem")
                        .HasColumnType("integer")
                        .HasColumnName("status_order_item");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_guid");

                    b.HasKey("Guid")
                        .HasName("pk_order_items");

                    b.HasIndex("CreatedByGuid")
                        .HasDatabaseName("ix_order_items_created_by_guid");

                    b.HasIndex("MenuItemGuid")
                        .HasDatabaseName("ix_order_items_menu_item_guid");

                    b.HasIndex("OrderBillGuid")
                        .HasDatabaseName("ix_order_items_order_bill_guid");

                    b.HasIndex("UpdatedByGuid")
                        .HasDatabaseName("ix_order_items_updated_by_guid");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("TableUp.Domain.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_guid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_guid");

                    b.HasKey("Guid")
                        .HasName("pk_restaurants");

                    b.HasIndex("CreatedByGuid")
                        .HasDatabaseName("ix_restaurants_created_by_guid");

                    b.HasIndex("UpdatedByGuid")
                        .HasDatabaseName("ix_restaurants_updated_by_guid");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("TableUp.Domain.Entities.Table", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_guid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("number");

                    b.Property<Guid>("RestaurantGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_guid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TableToken")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("table_token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_guid");

                    b.HasKey("Guid")
                        .HasName("pk_tables");

                    b.HasIndex("CreatedByGuid")
                        .HasDatabaseName("ix_tables_created_by_guid");

                    b.HasIndex("RestaurantGuid")
                        .HasDatabaseName("ix_tables_restaurant_guid");

                    b.HasIndex("UpdatedByGuid")
                        .HasDatabaseName("ix_tables_updated_by_guid");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("TableUp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Guid")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TableUp.Domain.Entities.MenuCategory", b =>
                {
                    b.HasOne("TableUp.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_menu_categories_users_created_by_guid");

                    b.HasOne("TableUp.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_categories_restaurants_restaurant_guid");

                    b.HasOne("TableUp.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_menu_categories_users_updated_by_guid");

                    b.Navigation("CreatedBy");

                    b.Navigation("Restaurant");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TableUp.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("TableUp.Domain.Entities.MenuCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_menu_categories_category_guid");

                    b.HasOne("TableUp.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_users_created_by_guid");

                    b.HasOne("TableUp.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_users_updated_by_guid");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TableUp.Domain.Entities.OrderBill", b =>
                {
                    b.HasOne("TableUp.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_bills_users_created_by_guid");

                    b.HasOne("TableUp.Domain.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_bills_tables_table_guid");

                    b.HasOne("TableUp.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_bills_users_updated_by_guid");

                    b.Navigation("CreatedBy");

                    b.Navigation("Table");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TableUp.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("TableUp.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_users_created_by_guid");

                    b.HasOne("TableUp.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_menu_items_menu_item_guid");

                    b.HasOne("TableUp.Domain.Entities.OrderBill", "OrderBill")
                        .WithMany("BillItems")
                        .HasForeignKey("OrderBillGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_order_bills_order_bill_guid");

                    b.HasOne("TableUp.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_users_updated_by_guid");

                    b.Navigation("CreatedBy");

                    b.Navigation("MenuItem");

                    b.Navigation("OrderBill");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TableUp.Domain.Entities.Restaurant", b =>
                {
                    b.HasOne("TableUp.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_restaurants_users_created_by_guid");

                    b.HasOne("TableUp.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_restaurants_users_updated_by_guid");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TableUp.Domain.Entities.Table", b =>
                {
                    b.HasOne("TableUp.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tables_users_created_by_guid");

                    b.HasOne("TableUp.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tables_restaurants_restaurant_guid");

                    b.HasOne("TableUp.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tables_users_updated_by_guid");

                    b.Navigation("CreatedBy");

                    b.Navigation("Restaurant");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TableUp.Domain.Entities.OrderBill", b =>
                {
                    b.Navigation("BillItems");
                });
#pragma warning restore 612, 618
        }
    }
}
